const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const progress=$('#progressBar'),particles=$('#particles');let count=0;
const io=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal').forEach(e=>io.observe(e));
window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${h?scrollY/h*100:0}%`},{passive:true});
$('#begin').onclick=()=>$('#story').scrollIntoView({behavior:'smooth'});$('#replay').onclick=()=>scrollTo({top:0,behavior:'smooth'});
$('#noteBtn').onclick=()=>{const m=$('#noteModal');m.classList.add('open');m.setAttribute('aria-hidden','false')};const close=()=>{$('#noteModal').classList.remove('open');$('#noteModal').setAttribute('aria-hidden','true')};$('#closeNote').onclick=close;$('.modal-backdrop').onclick=close;document.addEventListener('keydown',e=>e.key==='Escape'&&close());
const cursor=$('#cursorGlow');window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'},{passive:true});
$$('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{if(innerWidth<800)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateY(${x*7}deg) rotateX(${-y*7}deg) translateY(-4px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
function burst(x,y,n=18){for(let i=0;i<n;i++){const s=document.createElement('i');s.className='spark';s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--x',`${(Math.random()-.5)*260}px`);s.style.setProperty('--y',`${(Math.random()-.5)*260}px`);s.style.width=s.style.height=(2+Math.random()*5)+'px';particles.appendChild(s);setTimeout(()=>s.remove(),1500)}}
$('#magicStar').onclick=e=>{count++;$('#tapCount').textContent=count;const r=e.currentTarget.getBoundingClientRect();burst(r.left+r.width/2,r.top+r.height/2,22)};$('#finalHeart').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();burst(r.left+r.width/2,r.top+r.height/2,34);e.currentTarget.animate([{transform:'scale(1)'},{transform:'scale(1.35)'},{transform:'scale(1)'}],{duration:500})};
document.addEventListener('click',e=>{if(e.target.closest('button'))return;if(Math.random()<.2)burst(e.clientX,e.clientY,7)});
let audioCtx=null,ambient=false;$('#musicBtn').onclick=()=>{ambient=!ambient;$('#musicBtn').textContent=ambient?'♫':'♪';if(ambient){audioCtx=audioCtx||new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=261.63;g.gain.value=.015;o.connect(g).connect(audioCtx.destination);o.start();window._tone={o,g}}else if(window._tone){window._tone.g.stop();window._tone.o.stop();window._tone=null}};
// Soft entrance spark field
for(let i=0;i<30;i++){const s=document.createElement('i');s.className='spark';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.opacity=.25;s.style.setProperty('--x',(Math.random()*80-40)+'px');s.style.setProperty('--y',(Math.random()*80-40)+'px');particles.appendChild(s);setTimeout(()=>s.remove(),1400)}