const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const progress=$('#progressBar'),particles=$('#particles'),canvas=$('#universe'),ctx=canvas.getContext('2d'),cursor=$('#cursorGlow'),nebula=$('#nebula');let taps=0,stars=[],px=innerWidth/2,py=innerHeight/2,tx=px,ty=py,audio=null,playing=false;
const portal=$('#portal');$('#enterUniverse').onclick=()=>{portal.classList.add('hidden');explode(innerWidth/2,innerHeight/2,120,2);setTimeout(()=>$('#story').scrollIntoView({behavior:'smooth'}),800);startSound()};
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));
function scroll(){let h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h?scrollY/h*100:0)+'%';nebula.style.transform=`translate(${(px/innerWidth-.5)*25}px,${-scrollY*.02}px)`}addEventListener('scroll',scroll,{passive:true});scroll();
addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;cursor.style.left=tx+'px';cursor.style.top=ty+'px';$('#coords').textContent=`${Math.round(tx)} · ${Math.round(ty)}`});addEventListener('pointerdown',e=>explode(e.clientX,e.clientY,10,.6));
$$('.tilt').forEach(c=>{c.onpointermove=e=>{if(innerWidth<800)return;let r=c.getBoundingClientRect(),x=e.clientX/r.width-r.left/r.width-.5,y=e.clientY/r.height-r.top/r.height-.5;c.style.transform=`perspective(900px) rotateY(${x*10}deg) rotateX(${-y*10}deg) translateY(-7px) scale(1.01)`};c.onpointerleave=()=>c.style.transform='' });
$$('.magnetic').forEach(b=>{b.onpointermove=e=>{let r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.14}px,${(e.clientY-r.top-r.height/2)*.14}px)`};b.onpointerleave=()=>b.style.transform=''});
function explode(x,y,n=25,p=1){for(let i=0;i<n;i++){let s=document.createElement('i'),a=Math.random()*Math.PI*2,d=(60+Math.random()*260)*p;s.className='spark';s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--x',Math.cos(a)*d+'px');s.style.setProperty('--y',Math.sin(a)*d+'px');s.style.width=s.style.height=2+Math.random()*6+'px';s.style.animationDuration=.6+Math.random()*1+'s';particles.appendChild(s);setTimeout(()=>s.remove(),1800)}}
function wave(x,y){let e=document.createElement('i');e.style.cssText=`position:fixed;left:${x}px;top:${y}px;width:20px;height:20px;border:1px solid #dfadff;border-radius:50%;transform:translate(-50%,-50%);z-index:15;pointer-events:none;transition:.9s;box-shadow:0 0 40px #c875ff`;particles.appendChild(e);requestAnimationFrame(()=>{e.style.transform='translate(-50%,-50%) scale(24)';e.style.opacity=0});setTimeout(()=>e.remove(),1000)}
function popup(t,s){let e=$('#easter');e.querySelector('strong').textContent=t;e.querySelector('small').textContent=s;e.classList.add('show');clearTimeout(window.pop);window.pop=setTimeout(()=>e.classList.remove('show'),2600)}
$('#magicStar').onclick=e=>{taps++;$('#tapCount').textContent=taps;let r=e.currentTarget.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;explode(x,y,35+Math.min(taps,12)*6,1+taps*.04);wave(x,y);tone(250+taps*38,.07);if(taps===3)popup('SIGNAL FOUND','the universe noticed you.');if(taps===7)popup('SUPERNOVA','okay… you broke physics.');if(taps>=10)for(let i=0;i<5;i++)setTimeout(()=>explode(Math.random()*innerWidth,Math.random()*innerHeight,45,1.5),i*100)};
$('#finalHeart').onclick=e=>{let r=e.currentTarget.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;explode(x,y,130,2);wave(x,y);tone(523,.12,.25);e.currentTarget.animate([{transform:'scale(1)'},{transform:'scale(1.55)'},{transform:'scale(1)'}],{duration:700});popup('HEART TRANSMITTED','friendship signal successfully sent ✦')};
$('#begin').onclick=()=>$('#story').scrollIntoView({behavior:'smooth'});$('#replay').onclick=()=>location.reload();document.addEventListener('click',e=>{if(!e.target.closest('button')&&Math.random()<.3)explode(e.clientX,e.clientY,9,.6)});
$('#noteBtn').onclick=()=>{$('#noteModal').classList.add('open');$('#noteModal').setAttribute('aria-hidden','false');explode(innerWidth/2,innerHeight/2,30)};const close=()=>{$('#noteModal').classList.remove('open');$('#noteModal').setAttribute('aria-hidden','true')};$('#closeNote').onclick=close;$('.modal-backdrop').onclick=close;document.onkeydown=e=>{if(e.key==='Escape')close();if(e.key.toLowerCase()==='q')popup('QUIN PROTOCOL','secret key accepted ✦')};
function resize(){let d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.min(560,Math.floor(innerWidth*innerHeight/3800))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,z:.2+Math.random()*.9,r:.4+Math.random()*1.4,a:.15+Math.random()*.7,p:Math.random()*6.28}))}function frame(){px+=(tx-px)*.08;py+=(ty-py)*.08;ctx.clearRect(0,0,innerWidth,innerHeight);let t=performance.now()/1000;for(let s of stars){let dx=px-s.x,dy=py-s.y,dist=Math.hypot(dx,dy);if(dist<180){let f=(180-dist)/180*.75;s.x-=dx/dist*f*s.z;s.y-=dy/dist*f*s.z}if(s.x<-8)s.x=innerWidth+8;if(s.x>innerWidth+8)s.x=-8;if(s.y<-8)s.y=innerHeight+8;if(s.y>innerHeight+8)s.y=-8;ctx.globalAlpha=s.a*(.6+.4*Math.sin(t*1.6+s.p));ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s.x,s.y,s.r*s.z,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;requestAnimationFrame(frame)}addEventListener('resize',resize);resize();frame();
function startSound(){if(playing)return;playing=true;$('#musicBtn').textContent='♫';audio=audio||new(window.AudioContext||window.webkitAudioContext)();let m=audio.createGain();m.gain.value=.01;m.connect(audio.destination);window.pad={m,n:[130.81,164.81,196,246.94].map((f,i)=>{let o=audio.createOscillator(),g=audio.createGain();o.type=i?'sine':'triangle';o.frequency.value=f;g.gain.value=.16/(i+1);o.connect(g).connect(m);o.start();return o})}}function stopSound(){playing=false;$('#musicBtn').textContent='♪';if(window.pad){window.pad.m.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.3);setTimeout(()=>window.pad.n.forEach(o=>o.stop()),400);window.pad=null}}$('#musicBtn').onclick=()=>playing?stopSound():startSound();function tone(f,d=.05,v=.1){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d+.02)}
for(let i=0;i<60;i++){let s=document.createElement('i');s.className='spark';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.opacity=.16;s.style.setProperty('--x',(Math.random()*100-50)+'px');s.style.setProperty('--y',(Math.random()*100-50)+'px');particles.appendChild(s);setTimeout(()=>s.remove(),2000)}