const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const canvas=$('#universe'),ctx=canvas.getContext('2d'),particles=$('#particles'),cursor=$('#cursorGlow'),nebula=$('#nebula'),progress=$('#progressBar');let stars=[],px=innerWidth/2,py=innerHeight/2,tx=px,ty=py,taps=0,playing=false,audio=null;
const portal=$('#portal');
$('#enterUniverse').onclick=()=>{portal.classList.add('hidden');universeBurst(innerWidth/2,innerHeight/2,180,2.8);setTimeout(()=>$('#story').scrollIntoView({behavior:'smooth'}),900);startSound()};
$('#begin').onclick=()=>$('#story').scrollIntoView({behavior:'smooth'});$('#replay').onclick=()=>location.reload();
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal').forEach(e=>io.observe(e));
addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h?scrollY/h*100:0)+'%';nebula.style.transform=`translate(${(px/innerWidth-.5)*25}px,${-scrollY*.02}px)`},{passive:true});
addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;cursor.style.left=tx+'px';cursor.style.top=ty+'px';$('#coords').textContent=`${Math.round(tx)} · ${Math.round(ty)}`},{passive:true});
addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;universeBurst(e.clientX,e.clientY,16,.8);tone(360,.04,.06)});
function universeBurst(x,y,n=80,p=1){for(let i=0;i<n;i++){const s=document.createElement('i');s.className='spark';s.style.left=x+'px';s.style.top=y+'px';const a=Math.random()*Math.PI*2,d=(90+Math.random()*360)*p;s.style.setProperty('--x',Math.cos(a)*d+'px');s.style.setProperty('--y',Math.sin(a)*d+'px');s.style.width=s.style.height=(2+Math.random()*7)+'px';s.style.animationDuration=(.7+Math.random()*1.1)+'s';particles.appendChild(s);setTimeout(()=>s.remove(),2100)}const w=document.createElement('i');w.style.cssText=`position:fixed;left:${x}px;top:${y}px;width:12px;height:12px;border:1px solid #e8c1ff;border-radius:50%;transform:translate(-50%,-50%);pointer-events:none;z-index:15;box-shadow:0 0 50px #b96cff;transition:1.1s cubic-bezier(.1,.8,.2,1)`;particles.appendChild(w);requestAnimationFrame(()=>{w.style.transform='translate(-50%,-50%) scale(55)';w.style.opacity='0'});setTimeout(()=>w.remove(),1200)}
$$('.tilt').forEach(c=>{c.onpointermove=e=>{if(innerWidth<800)return;const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`perspective(900px) rotateY(${x*10}deg) rotateX(${-y*10}deg) translateY(-7px) scale(1.01)`};c.onpointerleave=()=>c.style.transform=''});
$$('.magnetic').forEach(b=>{b.onpointermove=e=>{const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.14}px,${(e.clientY-r.top-r.height/2)*.14}px)`};b.onpointerleave=()=>b.style.transform=''});
function popup(t,s){const e=$('#easter');e.querySelector('strong').textContent=t;e.querySelector('small').textContent=s;e.classList.add('show');clearTimeout(window.pop);window.pop=setTimeout(()=>e.classList.remove('show'),2600)}
$('#magicStar').onclick=e=>{taps++;$('#tapCount').textContent=taps;const r=e.currentTarget.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;universeBurst(x,y,70+Math.min(taps,12)*12,1+taps*.08);tone(240+taps*42,.08,.15);if(taps===3)popup('SIGNAL FOUND','the universe noticed you.');if(taps===7)popup('SUPERNOVA','you broke physics.');if(taps>=10){$('#hudState').textContent='SUPERNOVA MODE';for(let i=0;i<7;i++)setTimeout(()=>universeBurst(Math.random()*innerWidth,Math.random()*innerHeight,70,1.7),i*90)}};
$('#finalHeart').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();universeBurst(r.left+r.width/2,r.top+r.height/2,220,3);tone(523,.14,.25);e.currentTarget.animate([{transform:'scale(1)'},{transform:'scale(1.6)'},{transform:'scale(1)'}],{duration:750});popup('HEART TRANSMITTED','friendship signal successfully sent ✦')};
$('#noteBtn').onclick=()=>{$('#noteModal').classList.add('open');$('#noteModal').setAttribute('aria-hidden','false');universeBurst(innerWidth/2,innerHeight/2,45,1)};const close=()=>{$('#noteModal').classList.remove('open');$('#noteModal').setAttribute('aria-hidden','true')};$('#closeNote').onclick=close;$('.modal-backdrop').onclick=close;document.onkeydown=e=>{if(e.key==='Escape')close();if(e.key.toLowerCase()==='q')popup('QUIN PROTOCOL','secret key accepted ✦')};
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.min(620,Math.floor(innerWidth*innerHeight/3400))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,z:.15+Math.random()*.95,r:.3+Math.random()*1.7,a:.12+Math.random()*.75,p:Math.random()*6.28}))}function frame(){px+=(tx-px)*.08;py+=(ty-py)*.08;ctx.clearRect(0,0,innerWidth,innerHeight);const t=performance.now()/1000;for(const s of stars){const dx=px-s.x,dy=py-s.y,dist=Math.hypot(dx,dy);if(dist<190){const f=(190-dist)/190*.9;s.x-=dx/(dist||1)*f*s.z;s.y-=dy/(dist||1)*f*s.z}if(s.x<-8)s.x=innerWidth+8;if(s.x>innerWidth+8)s.x=-8;if(s.y<-8)s.y=innerHeight+8;if(s.y>innerHeight+8)s.y=-8;ctx.globalAlpha=s.a*(.55+.45*Math.sin(t*1.7+s.p));ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s.x,s.y,s.r*s.z,0,Math.PI*2);ctx.fill();if(s.z>.82&&Math.sin(t*1.7+s.p)>.92){ctx.globalAlpha=.25;ctx.strokeStyle='#d9a5ff';ctx.beginPath();ctx.moveTo(s.x-6,s.y);ctx.lineTo(s.x+6,s.y);ctx.moveTo(s.x,s.y-6);ctx.lineTo(s.x,s.y+6);ctx.stroke()}}ctx.globalAlpha=1;requestAnimationFrame(frame)}addEventListener('resize',resize);resize();frame();
function startSound(){if(playing)return;playing=true;$('#musicBtn').textContent='♫';audio=audio||new(window.AudioContext||window.webkitAudioContext)();const m=audio.createGain();m.gain.value=.012;m.connect(audio.destination);window.pad={m,n:[130.81,164.81,196,246.94].map((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type=i?'sine':'triangle';o.frequency.value=f;g.gain.value=.16/(i+1);o.connect(g).connect(m);o.start();return o})}}function stopSound(){playing=false;$('#musicBtn').textContent='♪';if(window.pad){window.pad.m.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.3);setTimeout(()=>window.pad.n.forEach(o=>o.stop()),400);window.pad=null}}$('#musicBtn').onclick=()=>playing?stopSound():startSound();function tone(f,d=.05,v=.1){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d+.02)}
for(let i=0;i<90;i++){const s=document.createElement('i');s.className='spark';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.opacity=.15;s.style.setProperty('--x',(Math.random()*140-70)+'px');s.style.setProperty('--y',(Math.random()*140-70)+'px');s.style.animationDuration=(.8+Math.random()*1.6)+'s';particles.appendChild(s);setTimeout(()=>s.remove(),2500)}